package name.lizhe.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2017-06-13T17:43:38.792+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://service.lizhe.name/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorld {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://service.lizhe.name/", partName = "return")
    public java.lang.String speak(
        @WebParam(partName = "arg0", name = "arg0")
        Student arg0
    );
}
